clean:
    rm -rf jnk

build:
    cargo run
    mkdir jnk
    cp jnk.tcl jnk/.
    cp ports.xdc jnk/.
    cp clocks.xdc jnk/.
    cd jnk && vivado -mode batch -source jnk.tcl

binify:
    cd jnk && echo "all:{ system.bit }" > system.bif
    cd jnk && bootgen -image system.bif -arch zynq -process_bitstream bin -w -o system.bin
    